export const resList = [
  {
    id: "27739",
    name: "Cafe Niloufer Classic",
    cloudinaryImageId: "882922742c3b3abc54ae9fde6d6c236d",
    locality: "Oshiwara",
    areaName: "Red Hills",
    costForTwo: "₹150 for two",
    cuisines: ["Bakery", "Beverages", "Snacks", "Desserts"],
    avgRating: 3.5,
  },
  {
    id: "32129",
    name: "Burger King",
    cloudinaryImageId: "e33e1d3ba7d6b2bb0d45e1001b731fcf",
    locality: "Himayath Nagar",
    areaName: "Himayath Nagar",
    costForTwo: "₹350 for two",
    cuisines: ["Burgers", "American"],
    avgRating: 4.2,
  },
  {
    id: "308707",
    name: "Krispy Kreme",
    cloudinaryImageId: "hpu33j9x8coy57yay02s",
    locality: "GVK One Mall",
    areaName: "Banjara Hills",
    costForTwo: "₹170 for two",
    cuisines: ["Desserts", "Beverages"],
    avgRating: 3.6,
  },
  {
    id: "12046",
    name: "Subway",
    cloudinaryImageId: "1ace5fa65eff3e1223feb696c956b38b",
    locality: "Telangana",
    areaName: "Himayatnagar",
    costForTwo: "₹350 for two",
    cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
    avgRating: 4.1,
  },
  {
    id: "7203",
    name: "Taj Mahal-Abids",
    cloudinaryImageId: "xtxi8kws7lmnwfardw0b",
    locality: "Abids Road",
    areaName: "Koti",
    costForTwo: "₹300 for two",
    cuisines: ["North Indian", "Chinese", "South Indian"],
    avgRating: 4.5,
  },
  {
    id: "17104",
    name: "KFC",
    cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
    locality: "Prime Plaza",
    areaName: "Himayatnagar",
    costForTwo: "₹400 for two",
    cuisines: ["Burgers", "Biryani", "American", "Snacks", "Fast Food"],
    avgRating: 4.2,
  },
];
